VenusProtocol/protocol-reserve

- hardhat.config.ts
- package.json
- yarn.lock
The following dependencies are not used:
* @venusprotocol/venus-protocol
* @venusprotocol/isolated-pools
Moreover, I'm including the `typechain` folder in the published package
> feat: remove unneeded dependencies

- contracts/Interfaces/IComptroller.sol
- contracts/Interfaces/IRiskFund.sol
- contracts/ProtocolReserve/RiskFundStorage.sol
- contracts/ProtocolReserve/RiskFundV2.sol
- contracts/Test/Mocks/MockRiskFundConverter.sol
- contracts/TokenConverter/AbstractTokenConverter.sol
- contracts/TokenConverter/RiskFundConverter.sol
- tests/ProtocolReserve/RiskFundV2.ts
- tests/TokenConverter/RiskFundConverter.ts
Resolves:
- VEN-1827
- VEN-1828
- VEN-1834
> [VEN-1827] [VEN-1828] [VEN-1834] RiskFundConverter and RiskFundV2 

- contracts/ProtocolReserve/RiskFundStorage.sol
- contracts/ProtocolReserve/RiskFundV2.sol
- contracts/TokenConverter/AbstractTokenConverter.sol
- contracts/TokenConverter/RiskFundConverter.sol
- tests/TokenConverter/AbstractTokenConverter.ts
> [VEN-1911]: PeckShield audit fix for token converter

- contracts/TokenConverter/AbstractTokenConverter.sol
- tests/TokenConverter/AbstractTokenConverter.ts
This PR contains getter functions for **getAmountIn** and **getAmountOut** in **AbstractTokenConverter**.
> [VEN-1936]: View functions to getAmountIn and getAmountOut

- contracts/ProtocolReserve/ProtocolShareReserve.sol
PSP-01 | Unnecessary Storage Read Access in For Loop 
Resolves VEN-1938
> [VEN-1938]: Certik audit fix PSP-01

- contracts/ProtocolReserve/ProtocolShareReserve.sol
- package.json
- yarn.lock
Related to VEN-1080. It replaces the dependency with the isolated-pools package, using the new solidity-utilities package.
> [VEN-1080]: replace dependency of isolated-pools

- contracts/Interfaces/IRiskFund.sol
- contracts/ProtocolReserve/RiskFundV2.sol
- contracts/ProtocolReserve/XVSVaultTreasury.sol
- contracts/Test/Mocks/MockConverter.sol
- contracts/TokenConverter/AbstractTokenConverter.sol
- contracts/TokenConverter/RiskFundConverter.sol
- contracts/TokenConverter/SingleTokenConverter.sol
- contracts/TokenConverter/XVSVaultConverter.sol
- contracts/Utils/Validators.sol
- deploy/001-risk-fund-converter.ts
- tests/ProtocolReserve/RiskFundV2.ts
- tests/TokenConverter/AbstractTokenConverter.ts
- tests/TokenConverter/RiskFundConverter.ts
- tests/TokenConverter/XVSVaultConverter.ts
Resolves:
- VEN-2043: Certik Audit fixes for token converter.      
- VEN-2064: Convert `XVSVaultConverter` to `SingleTokenConverter`
- Refactored deployment scripts for the `RiskFundConverter`
> [VEN-2043]: Certik audit fix for token converter

- contracts/Test/Mocks/MockRiskFundConverter.sol
- contracts/TokenConverter/AbstractTokenConverter.sol
- contracts/TokenConverter/ConverterNetwork.sol
- contracts/TokenConverter/RiskFundConverter.sol
- contracts/TokenConverter/SingleTokenConverter.sol
- tests/TokenConverter/AbstractTokenConverter.ts
- tests/TokenConverter/ConverterNetwork.ts
- tests/TokenConverter/RiskFundConverter.ts
> [VEN -2140] - Certik fixes for private conversions

- package.json
Removes exports from package.json to allow for importing non modules
> fix: remove exports from package.json

- hardhat.config.ts
> [VEN-2197]: unify the use of the env variable DEPLOYER_PRIVATE_KEY

- deploy/1-deploy.ts
> fix: fix build with missing type

- .github/workflows/ci.yml
- deploy/1-deploy.ts
Add CI check that deployment scripts can run successfully
> ci: check that deployment scripts run

- .solhint.json
- hardhat.config.ts
Remove unsued solidity version 0.5.16
> fix: remove compiler version 0.5.16

- contracts/TokenConverter/AbstractTokenConverter.sol
This PR contains the audit fix regarding `N-05` suggested by OZ.
> OZ audit fix for Private Conversion

- package.json
- yarn.lock
> [VEN-1825]: update deps to the stable versions

- deploy/003-xvs-vault-teasury.ts
- deploy/005-converter-network.ts
- yarn.lock
For consistency use es6 modules in deployment scripts
> fix: use ex6 modules

- package.json
- tsconfig.json
- yarn.lock
Compile typechain so it can be imported as commonjs
> fix: compile typechain for distribution

- package.json
Compile typechain before deploying.
> Compile before deploy

- hardhat.config.ts
- package.json
- yarn.lock
Remove unnecessary Isolated Pools dependency
> refactor: remove unnecessary isolated pools dep

- package.json
- yarn.lock
Updates package.json to include `typechain` when packagain
> feat: distrubute typechain contract types

- deploy/000-psr.ts
- deploy/001-risk-fund-v2.ts
- deploy/002-risk-fund-converter.ts
- deploy/003-xvs-vault-treasury.ts
- deploy/004-single-token-converter.ts
- deploy/005-converter-network.ts
- hardhat.config.ts
- helpers/utils.ts
Update deployment scripts so they run successfully in this project and when imported.
There is one caveat that when using the set of Venus Deployments BTCB is missing so they will need to manually deploy that token. Otherwise these will work.
> refactor!: support project and full protocol hardhat deploy

- .eslinttsconfigrc
- hardhat.config.ts
- hardhat.config.zksync.ts
- package.json
- tsconfig.json
- type-extensions.ts
- yarn.lock
> feat: update dependencies

- yarn.lock
> Release back (fix)

- contracts/Interfaces/IProtocolShareReserve.sol
- yarn.lock
> [VEN-2985][VEN-2887]: Add incomeType for ERC4626 rewards and FlashLoan in PSR
